-- Generated from schema.prisma for PostgreSQL 18
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET check_function_bodies = false;
SET client_min_messages = warning;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'Rol') THEN
    CREATE TYPE "Rol" AS ENUM ('ADMINISTRADOR', 'PSICOLOGO', 'TRABAJADOR_SOCIAL', 'ASISTENTE', 'BENEFICIARIO');
  END IF;
END$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'EstadoRegistro') THEN
    CREATE TYPE "EstadoRegistro" AS ENUM ('REGISTRO_INICIAL', 'EN_EVALUACION_ADMINISTRADOR', 'BENEFICIARIO_ACTIVO', 'CASO_RECHAZADO');
  END IF;
END$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'EstadoBeneficiario') THEN
    CREATE TYPE "EstadoBeneficiario" AS ENUM ('ACTIVO', 'INACTIVO', 'RECUPERADO', 'FALLECIDO');
  END IF;
END$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'NivelVulnerabilidad') THEN
    CREATE TYPE "NivelVulnerabilidad" AS ENUM ('BAJO', 'MEDIO', 'ALTO');
  END IF;
END$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'EstadoSesionQuimio') THEN
    CREATE TYPE "EstadoSesionQuimio" AS ENUM ('PROGRAMADA', 'REALIZADA', 'REPROGRAMADA', 'NO_ASISTIO');
  END IF;
END$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'EstadoMedico') THEN
    CREATE TYPE "EstadoMedico" AS ENUM ('EN_TRATAMIENTO', 'VIGILANCIA', 'PALIATIVO', 'ABANDONO', 'FALLECIDO');
  END IF;
END$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'FaseTratamiento') THEN
    CREATE TYPE "FaseTratamiento" AS ENUM ('INDUCCION', 'CONSOLIDACION', 'INTENSIFICACION', 'MANTENIMIENTO', 'POST_TRATAMIENTO');
  END IF;
END$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'TipoAyuda') THEN
    CREATE TYPE "TipoAyuda" AS ENUM ('MEDICAMENTOS', 'QUIMIOTERAPIA', 'ANALISIS_EXAMENES', 'OTRO');
  END IF;
END$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'PrioridadSolicitud') THEN
    CREATE TYPE "PrioridadSolicitud" AS ENUM ('BAJA', 'MEDIA', 'ALTA', 'URGENTE');
  END IF;
END$$;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'EstadoSolicitud') THEN
    CREATE TYPE "EstadoSolicitud" AS ENUM ('PENDIENTE', 'RECEPCIONADO', 'ENTREGADO', 'RECHAZADO');
  END IF;
END$$;

CREATE TABLE "Usuario" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" text NOT NULL,
  "email" text NOT NULL,
  "telefono" text NOT NULL,
  "pais" text NOT NULL,
  "password" text NOT NULL,
  "creadoEn" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "ci" text,
  "rol" "Rol",
  CONSTRAINT "uq_Usuario_email" UNIQUE ("email")
);

CREATE TABLE "Padre" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" text NOT NULL,
  "apellido" text NOT NULL,
  "telefono" text NOT NULL,
  "ci" text NOT NULL,
  "ubicacion" text NOT NULL
);

CREATE TABLE "Evento" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "titulo" text NOT NULL,
  "descripcion" text NOT NULL,
  "fecha" text NOT NULL,
  "ubicacion" text NOT NULL,
  "img" text NOT NULL
);

CREATE TABLE "Campana" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "titulo" text NOT NULL,
  "descripcion" text NOT NULL,
  "fecha" text NOT NULL,
  "multimedia" text NOT NULL,
  "recaudado" numeric,
  "previstro" numeric
);

CREATE TABLE "CodigoVerificacion" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" text NOT NULL,
  "codigo" text NOT NULL,
  "usado" boolean NOT NULL DEFAULT false,
  "expiraEn" timestamptz NOT NULL,
  "createdAt" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "@@index([email," text NOT NULL
);

CREATE TABLE "WhatsappTemplate" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigo" text NOT NULL,
  "plantilla" text NOT NULL,
  "descripcion" text,
  "createdAt" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "uq_WhatsappTemplate_codigo" UNIQUE ("codigo")
);

CREATE TABLE "Notificacion" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "usuarioId" integer NOT NULL,
  "emailDestinatario" text,
  "tipo" text NOT NULL,
  "prioridad" text NOT NULL DEFAULT 'normal',
  "titulo" text NOT NULL,
  "mensaje" text NOT NULL,
  "relacionadoTipo" text,
  "relacionadoId" integer,
  "leida" boolean NOT NULL DEFAULT false,
  "fechaLeida" timestamptz,
  "emailEnviado" boolean NOT NULL DEFAULT false,
  "fechaEmailEnviado" timestamptz,
  "createdAt" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "fk_Notificacion_usuarioId" FOREIGN KEY ("usuarioId") REFERENCES "Usuario"("id") ON DELETE CASCADE
);

CREATE TABLE "PacienteRegistro" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombreCompletoNino" text NOT NULL,
  "fechaNacimiento" timestamptz NOT NULL,
  "edad" integer NOT NULL,
  "ciNino" text,
  "diagnostico" text NOT NULL,
  "nombreCompletoTutor" text NOT NULL,
  "ciTutor" text NOT NULL,
  "parentesco" text NOT NULL,
  "telefonoTutor" text NOT NULL,
  "direccion" text NOT NULL,
  "emailTutor" text,
  "creadoPorId" integer NOT NULL,
  "fechaRegistro" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "motivoRechazo" text,
  "estado" "EstadoRegistro" NOT NULL DEFAULT 'REGISTRO_INICIAL',
  CONSTRAINT "fk_PacienteRegistro_creadoPorId" FOREIGN KEY ("creadoPorId") REFERENCES "Usuario"("id")
);

CREATE TABLE "Paciente" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" text NOT NULL,
  "apellido" text NOT NULL,
  "ciudad" text NOT NULL,
  "tipoCancer" text NOT NULL,
  "edad" integer NOT NULL,
  "idPadre" integer NOT NULL,
  "fechaRegistro" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "fk_Paciente_idPadre" FOREIGN KEY ("idPadre") REFERENCES "Padre"("id")
);

CREATE TABLE "UsuarioCompana" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idUsuario" integer,
  "nombreUsuario" text,
  "montoSuscripcion" integer NOT NULL,
  "idCompana" integer NOT NULL,
  "fecha" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "fk_UsuarioCompana_idCompana" FOREIGN KEY ("idCompana") REFERENCES "Campana"("id"),
  CONSTRAINT "fk_UsuarioCompana_idUsuario" FOREIGN KEY ("idUsuario") REFERENCES "Usuario"("id")
);

CREATE TABLE "Donaciones" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombreDonante" text NOT NULL,
  "cantidad" text NOT NULL,
  "metodoPago" text NOT NULL,
  "descripcion" text,
  "fecha" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "idCampana" integer,
  CONSTRAINT "fk_Donaciones_idCampana" FOREIGN KEY ("idCampana") REFERENCES "Campana"("id")
);

CREATE TABLE "Beneficiario" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pacienteRegistroId" integer NOT NULL,
  "codigoBeneficiario" text NOT NULL,
  "estadoBeneficiario" "EstadoBeneficiario" NOT NULL DEFAULT 'ACTIVO',
  "estadoMedico" "EstadoMedico" NOT NULL DEFAULT 'EN_TRATAMIENTO',
  "fechaAceptacion" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "aceptadoPorId" integer NOT NULL,
  "asignadoAId" integer,
  "historiaClinica" text,
  "fechaPrimerContacto" timestamptz,
  "nombreMedicoTratante" text,
  "especialidadMedico" text,
  "telefonoMedico" text,
  "institucionMedica" text,
  "faseTratamiento" "FaseTratamiento",
  "semanaProtocolo" integer,
  "esquemaTratamiento" text,
  "ultimaFechaControl" timestamptz,
  "proximaFechaControl" timestamptz,
  "frecuenciaControl" text,
  "fechaInicioVigilancia" timestamptz,
  "tiempoVigilanciaAnios" integer,
  "fechaUltimaAsistencia" timestamptz,
  "motivoAbandono" text,
  "notificadoDefensoria" boolean NOT NULL DEFAULT false,
  "fechaNotificacionDefensoria" timestamptz,
  "fechaFallecimiento" timestamptz,
  "causaFallecimiento" text,
  "alergiasMedicamentos" text,
  "complicaciones" text,
  "observacionesMedicas" text,
  "updatedAt" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "uq_Beneficiario_pacienteRegistroId" UNIQUE ("pacienteRegistroId"),
  CONSTRAINT "uq_Beneficiario_codigoBeneficiario" UNIQUE ("codigoBeneficiario"),
  CONSTRAINT "uq_Beneficiario_historiaClinica" UNIQUE ("historiaClinica"),
  CONSTRAINT "fk_Beneficiario_aceptadoPorId" FOREIGN KEY ("aceptadoPorId") REFERENCES "Usuario"("id"),
  CONSTRAINT "fk_Beneficiario_asignadoAId" FOREIGN KEY ("asignadoAId") REFERENCES "Usuario"("id"),
  CONSTRAINT "fk_Beneficiario_pacienteRegistroId" FOREIGN KEY ("pacienteRegistroId") REFERENCES "PacienteRegistro"("id") ON DELETE CASCADE
);

CREATE TABLE "EvaluacionSocial" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pacienteRegistroId" integer NOT NULL,
  "ingresoFamiliar" integer NOT NULL,
  "numPersonasHogar" integer NOT NULL,
  "tipoVivienda" integer NOT NULL,
  "situacionLaboralPadres" integer NOT NULL,
  "accesoSalud" integer NOT NULL,
  "gastosMedicosMensuales" integer NOT NULL,
  "puntajeTotal" integer NOT NULL,
  "nivelVulnerabilidad" "NivelVulnerabilidad" NOT NULL,
  "informeSocialPdf" text,
  "trabajadorSocialId" integer NOT NULL,
  "fechaEvaluacion" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "observaciones" text,
  CONSTRAINT "uq_EvaluacionSocial_pacienteRegistroId" UNIQUE ("pacienteRegistroId"),
  CONSTRAINT "fk_EvaluacionSocial_pacienteRegistroId" FOREIGN KEY ("pacienteRegistroId") REFERENCES "PacienteRegistro"("id") ON DELETE CASCADE,
  CONSTRAINT "fk_EvaluacionSocial_trabajadorSocialId" FOREIGN KEY ("trabajadorSocialId") REFERENCES "Usuario"("id")
);

CREATE TABLE "Tratamiento" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tipoTratamiento" text NOT NULL,
  "descripcion" text NOT NULL,
  "idPaciente" integer,
  "estado" boolean NOT NULL,
  "fecha" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "siguienteCita" timestamptz NOT NULL,
  CONSTRAINT "fk_Tratamiento_idPaciente" FOREIGN KEY ("idPaciente") REFERENCES "Paciente"("id")
);

CREATE TABLE "Recuperados" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idPaciente" integer NOT NULL,
  "diagnosis" text NOT NULL,
  "image" text NOT NULL,
  "quote" text NOT NULL,
  "recovered" text NOT NULL,
  "createdAt" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "fk_Recuperados_idPaciente" FOREIGN KEY ("idPaciente") REFERENCES "Paciente"("id")
);

CREATE TABLE "Ayuda" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "beneficiarioId" integer NOT NULL,
  "fechaAyuda" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "medicamentos" numeric NOT NULL DEFAULT 0,
  "analisisExamenes" numeric NOT NULL DEFAULT 0,
  "quimioterapia" numeric NOT NULL DEFAULT 0,
  "transporte" numeric NOT NULL DEFAULT 0,
  "alimentacion" numeric NOT NULL DEFAULT 0,
  "otros" numeric NOT NULL DEFAULT 0,
  "totalAyuda" numeric NOT NULL,
  "observaciones" text,
  "registradoPorId" integer NOT NULL,
  "createdAt" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "fk_Ayuda_beneficiarioId" FOREIGN KEY ("beneficiarioId") REFERENCES "Beneficiario"("id") ON DELETE CASCADE,
  CONSTRAINT "fk_Ayuda_registradoPorId" FOREIGN KEY ("registradoPorId") REFERENCES "Usuario"("id")
);

CREATE TABLE "SesionQuimioterapia" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "beneficiarioId" integer NOT NULL,
  "numeroSesion" integer NOT NULL,
  "fechaProgramada" timestamptz NOT NULL,
  "fechaRealizada" timestamptz,
  "estado" "EstadoSesionQuimio" NOT NULL DEFAULT 'PROGRAMADA',
  "observaciones" text,
  "createdAt" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "fk_SesionQuimioterapia_beneficiarioId" FOREIGN KEY ("beneficiarioId") REFERENCES "Beneficiario"("id") ON DELETE CASCADE
);

CREATE TABLE "SolicitudAyuda" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "codigoSolicitud" text NOT NULL,
  "beneficiarioId" integer NOT NULL,
  "solicitadoPorId" integer NOT NULL,
  "fechaSolicitud" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "prioridad" "PrioridadSolicitud" NOT NULL DEFAULT 'MEDIA',
  "tipoAyuda" "TipoAyuda" NOT NULL,
  "numeroReceta" text,
  "fechaReceta" timestamptz,
  "medicoPrescriptor" text,
  "recetaPdf" text,
  "detalleSolicitud" text NOT NULL,
  "costoEstimado" numeric,
  "observaciones" text,
  "estado" "EstadoSolicitud" NOT NULL DEFAULT 'PENDIENTE',
  "revisadoPorId" integer,
  "fechaRevision" timestamptz,
  "motivoRechazo" text,
  "fechaEntrega" timestamptz,
  "lugarEntrega" text,
  "costoReal" numeric,
  "proveedor" text,
  "facturaPdf" text,
  "createdAt" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "instruccionesEntrega" text,
  "montoAprobado" numeric,
  CONSTRAINT "uq_SolicitudAyuda_codigoSolicitud" UNIQUE ("codigoSolicitud"),
  CONSTRAINT "fk_SolicitudAyuda_beneficiarioId" FOREIGN KEY ("beneficiarioId") REFERENCES "Beneficiario"("id") ON DELETE CASCADE,
  CONSTRAINT "fk_SolicitudAyuda_revisadoPorId" FOREIGN KEY ("revisadoPorId") REFERENCES "Usuario"("id"),
  CONSTRAINT "fk_SolicitudAyuda_solicitadoPorId" FOREIGN KEY ("solicitadoPorId") REFERENCES "Usuario"("id")
);

-- Indexes for foreign keys (recommended)
CREATE INDEX IF NOT EXISTS "idx_Donaciones_idCampana" ON "Donaciones" ("idCampana");
CREATE INDEX IF NOT EXISTS "idx_Paciente_idPadre" ON "Paciente" ("idPadre");
CREATE INDEX IF NOT EXISTS "idx_Recuperados_idPaciente" ON "Recuperados" ("idPaciente");
CREATE INDEX IF NOT EXISTS "idx_Tratamiento_idPaciente" ON "Tratamiento" ("idPaciente");
CREATE INDEX IF NOT EXISTS "idx_UsuarioCompana_idCompana" ON "UsuarioCompana" ("idCompana");
CREATE INDEX IF NOT EXISTS "idx_UsuarioCompana_idUsuario" ON "UsuarioCompana" ("idUsuario");
CREATE INDEX IF NOT EXISTS "idx_PacienteRegistro_creadoPorId" ON "PacienteRegistro" ("creadoPorId");
CREATE INDEX IF NOT EXISTS "idx_EvaluacionSocial_pacienteRegistroId" ON "EvaluacionSocial" ("pacienteRegistroId");
CREATE INDEX IF NOT EXISTS "idx_EvaluacionSocial_trabajadorSocialId" ON "EvaluacionSocial" ("trabajadorSocialId");
CREATE INDEX IF NOT EXISTS "idx_Beneficiario_aceptadoPorId" ON "Beneficiario" ("aceptadoPorId");
CREATE INDEX IF NOT EXISTS "idx_Beneficiario_asignadoAId" ON "Beneficiario" ("asignadoAId");
CREATE INDEX IF NOT EXISTS "idx_Beneficiario_pacienteRegistroId" ON "Beneficiario" ("pacienteRegistroId");
CREATE INDEX IF NOT EXISTS "idx_Ayuda_beneficiarioId" ON "Ayuda" ("beneficiarioId");
CREATE INDEX IF NOT EXISTS "idx_Ayuda_registradoPorId" ON "Ayuda" ("registradoPorId");
CREATE INDEX IF NOT EXISTS "idx_SesionQuimioterapia_beneficiarioId" ON "SesionQuimioterapia" ("beneficiarioId");
CREATE INDEX IF NOT EXISTS "idx_SolicitudAyuda_beneficiarioId" ON "SolicitudAyuda" ("beneficiarioId");
CREATE INDEX IF NOT EXISTS "idx_SolicitudAyuda_revisadoPorId" ON "SolicitudAyuda" ("revisadoPorId");
CREATE INDEX IF NOT EXISTS "idx_SolicitudAyuda_solicitadoPorId" ON "SolicitudAyuda" ("solicitadoPorId");
CREATE INDEX IF NOT EXISTS "idx_Notificacion_usuarioId" ON "Notificacion" ("usuarioId");

-- updatedAt triggers (Prisma @updatedAt)
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW."updatedAt" = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS "trg_WhatsappTemplate_updatedAt" ON "WhatsappTemplate";
CREATE TRIGGER "trg_WhatsappTemplate_updatedAt"
BEFORE UPDATE ON "WhatsappTemplate"
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS "trg_PacienteRegistro_updatedAt" ON "PacienteRegistro";
CREATE TRIGGER "trg_PacienteRegistro_updatedAt"
BEFORE UPDATE ON "PacienteRegistro"
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS "trg_Beneficiario_updatedAt" ON "Beneficiario";
CREATE TRIGGER "trg_Beneficiario_updatedAt"
BEFORE UPDATE ON "Beneficiario"
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS "trg_EvaluacionSocial_updatedAt" ON "EvaluacionSocial";
CREATE TRIGGER "trg_EvaluacionSocial_updatedAt"
BEFORE UPDATE ON "EvaluacionSocial"
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS "trg_Recuperados_updatedAt" ON "Recuperados";
CREATE TRIGGER "trg_Recuperados_updatedAt"
BEFORE UPDATE ON "Recuperados"
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS "trg_Ayuda_updatedAt" ON "Ayuda";
CREATE TRIGGER "trg_Ayuda_updatedAt"
BEFORE UPDATE ON "Ayuda"
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS "trg_SesionQuimioterapia_updatedAt" ON "SesionQuimioterapia";
CREATE TRIGGER "trg_SesionQuimioterapia_updatedAt"
BEFORE UPDATE ON "SesionQuimioterapia"
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS "trg_SolicitudAyuda_updatedAt" ON "SolicitudAyuda";
CREATE TRIGGER "trg_SolicitudAyuda_updatedAt"
BEFORE UPDATE ON "SolicitudAyuda"
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

